select * from customer limit(20)
--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as revenue from customer group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount from customer where discount_applied ='yes' and purchase_amount>=( select avg(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating
select item_purchased,round(avg(review_rating:: numeric),2)as "average product rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Top 5 most purchased products
select item_purchased,count(*)as total_orders
from customer
group by item_purchased
order by total_orders desc
limit 5;

--Q5. Revenue generated by each category
SELECT
    category,
    SUM(Purchase_amount) AS revenue
FROM customer
GROUP BY category
ORDER BY revenue DESC;

--Q6. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

--Q7. Top 5 states by revenue
SELECT location,
       SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY location
ORDER BY revenue DESC
LIMIT 5;

--Q8. Discount usage percentage by product
SELECT item_purchased,
       ROUND(
       SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)
       *100.0/COUNT(*),2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC;

--Q9.Category contribution to total revenue (%)
SELECT category,
       ROUND(
       SUM("Purchase Amount (USD)")*100.0/
       SUM(SUM("Purchase Amount (USD)")) OVER(),2
       ) AS contribution_percentage
FROM customer
GROUP BY category;

--Q10. Highest spending customer
SELECT customer_id,
       SUM("Purchase Amount (USD)") AS total_spend
FROM customer
GROUP BY customer_id
ORDER BY total_spend DESC
LIMIT 1;

--Q11. Seasonal revenue analysis
SELECT season,
       SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY season
ORDER BY revenue DESC;

--Q12. Revenue rank of each category
SELECT category,
       SUM("Purchase Amount (USD)") AS revenue,
       RANK() OVER(
       ORDER BY SUM("Purchase Amount (USD)") DESC
       ) AS category_rank
FROM customer
GROUP BY category;

--Q13. Running revenue by customer
SELECT customer_id,
       "Purchase Amount (USD)",
       SUM("Purchase Amount (USD)")
       OVER(
       PARTITION BY customer_id
       ORDER BY customer_id
       ) AS running_total
FROM customer;
